# Generated by Django 4.2.7 on 2025-09-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
    ]
