# Generated by Django 4.2.7 on 2025-09-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'شراء', 'verbose_name_plural': 'المشتريات'},
        ),
    ]
