# Generated by Django 4.2.7 on 2025-09-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
    ]
