# Generated by Django 4.2.7 on 2025-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['vehicle_type', 'name'], 'verbose_name': 'فئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'مورد', 'verbose_name_plural': 'الموردين'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'شراء'), ('sale', 'بيع'), ('return_in', 'Return In'), ('return_out', 'Return Out'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Transfer'), ('damaged', 'Damaged'), ('lost', 'Lost')], max_length=20),
        ),
    ]
